### PR TITLE
Add handlers to viewer to save images and toggle 100k output mode.

### PR DESCRIPTION
**Pull request by sgieseking**
Since the opencv based UI has limited interaction capability, I used the keyboard input to save images and toggle the 100k output mode.  Not as nice as a menu or toolbar but I didn't want to completely change the application.
I had problems on my system with cv::waitKey returning with high bits set so the comparison to the characters was not working properly.  Others seems to have the same problem with this function.
I'm looking to add the ability to pause the imaging as well.

### CODE REVIEW

**Comment by tpanzarella** [comment]
@sgieseking Thanks for the PR. I think this *may* be a generally useful patch, but, I'd like to discuss a few things before I just go ahead and apply it.

**General Comment**
The `o3d3xx-viewer` application is intentionally minimalist. It is a quick and dirty way to visualize the images coming from the camera. However, I appreciate that perhaps adding some basic file I/O may not *bloat* the intent. You make mention it would be *better* to have things like menu or tool bars and again I can appreciate that. You also note that you'd like to add pausing. And, perhaps down the line, you may also want to add other things. That being said, before we go down a path of *bloat* if you would like to create a new github project that implements a more complete visualization application that uses this library, I highly encourage that and would be happy to make reference to it and link out to it in our README.  As a practical matter, the majority of `libo3d3xx` users are using this library underneath the [ROS interface](https://github.com/lovepark/o3d3xx-ros) and it then follows that the primary GUI for the library has really become [rviz](http://wiki.ros.org/rviz) which has *all the bells and whistles* most users would ever need. I don't want to reinvent that stuff here.

**PCL I/O Libraries**
You are bringing in the PCL io header `pcd_io.h`. Now, I have not built your code yet, but, likely this will have to link to `libpcl_io.so`. That being said, since all changes in the PR are localized to the `o3d3xx-viewer.cpp` file, no provisions were made to the build files to ensure these headers and libraries are available. Again, without actually verifying these things on my machine right now, I think at a minimum we would need something like this in the top-level `CMakeLists.txt` file where we check for PCL:

```
if (BUILD_EXE_VIEWER)
  find_package(PCL 1.7.1 REQUIRED COMPONENTS visualization io)
endif(BUILD_EXE_VIEWER)
```

And then in `src/bin/CMakeLists.txt`, where the viewer application gets built, we would have to link to `${PCL_IO_LIBRARIES}`.

**Hardcoded Paths**
Where you are actually doing the file writing, you have hardcoded in `./` as the location. We may want to make something like an optional `--output-dir` flag that defaults to something reasonable.

**printf vs. cout**
I think to remain consistent with the rest of the library we should use `std::cout`. In one spot you are using `printf` in another you are using `cout`.

**Not fully qualifying calls**
Again, for consistency in the library, we are *fully qualifying calls*. So, where you use `cout`, I'd like to see that be `std::cout`. When you are calling instance methods, I'd like to see `this->Foo()`. Again, it keeps things consistent with the rest of the code base.

**Unnecessarily Instantiating another Camera Instance**
In your `Toggle100kMode()` method, you are creating a new camera instance whereas the the `O3DViewer` class already has an instance to an `o3d3xx::Camera::Ptr` in `this->cam_`.

**Comment by tpanzarella** [comment]
Just to get another set of eyes and another perspective on things, I'm going to ping @graugans here to see if he has any opinions on the matters being discussed.

**Comment by sgieseking** [comment]
If there are parts that you want to include (or not any) that is fine.  I'm evaluating the camera for an application so I’m not sure how far my use will go.  I was not totally satisfied with the ifm application and wanted to try the 100K output mode.  I’m not using ROS and don’t really plan to.

Regarding a more complex UI, I’m not really going down that path now.  It would be nice if opencv had a little easier UI support for a menu or toolbar so that was the reason to choose the cv::waitKey input and just expand on it a bit.

The printf is junk left over from testing that I forgot that it was still in there.  I think it was from when cv::waitKey started to return values with high bits set so it was not processing the keys.

Didn’t notice cam_ as part of the class since it is not used frequently.  Obviously, better to use that.

**Comment by graugans** [comment]
@sgieseking May I ask what are your concerns about the **ifm Vision Assistance**?

For the **Hardcoded Paths** the suggested solution by defining a ``--output-dir`` is a good solution. May I suggest to use ``/tmp/`` instead of ``./`` as default location for the resulting images? Because ``/tmp`` will be cleaned on most Linux distribution during reboot.

I agree on @tpanzarella about his coding style and bloating concerns. 
The simple viewer is just quick way to test the configuration of the camera and to have a small example how to access the camera data. On the other hand dumping image data to disk may comes handy for reporting issues. @tpanzarella is there any image dump support implemented in your command line utilities already? 

The camera is able to handle up to 5 simultaneous data connections. So a simple command line tool  can be used to capture a single frame and dump the image to disk while displaying a live view with the viewer. The 100K mode can be activated by command line tools as-well.

**Comment by tpanzarella** [comment]
@graugans There is currently no support in `libo3d3xx` to dump images to disk. There are tools implemented by the ROS wrapper, but nothing in this library. I agree that `/tmp` is the sensible default location. I think to keep things simple, a reasonable approach would be to add something like pressing the space-bar to serialize all current image buffers to disk. As we do in the ROS tools, I'd suggest PCD for the Point Cloud and PNG for the OpenCV images.

We can add this to the TODO list for the current dev branch.

**Pull request closed without merging**
